from enum import Enum

class LicitacionStatus(str, Enum):
    PENDIENTE = "PENDIENTE"
    PROCESANDO_DOCUMENTOS = "PROCESANDO_DOCUMENTOS"
    DOCUMENTOS_PROCESADOS = "DOCUMENTOS_PROCESADOS"
    ERROR_PROCESO_DOCUMENTAL = "ERROR_PROCESO_DOCUMENTAL"
    REQUIERE_REVISION_TECNICA = "REQUIERE_REVISION_TECNICA"
    
    EXTRACCION_SEMANTICA_EN_PROCESO = "EXTRACCION_SEMANTICA_EN_PROCESO"
    EXTRACCION_SEMANTICA_COMPLETADA = "EXTRACCION_SEMANTICA_COMPLETADA"
    
    HOMOLOGACION_EN_PROCESO = "HOMOLOGACION_EN_PROCESO"
    HOMOLOGACION_COMPLETADA = "HOMOLOGACION_COMPLETADA"
    ERROR_EXTRACCION_SEMANTICA = "ERROR_EXTRACCION_SEMANTICA"
    
    # Estados operativos de usuario
    EN_ANALISIS = "EN_ANALISIS"
    EN_PREPARACION_OFERTA = "EN_PREPARACION_OFERTA"
    OFERTA_PRESENTADA = "OFERTA_PRESENTADA"
    EN_EVALUACION = "EN_EVALUACION"
    ADJUDICADA = "ADJUDICADA"
    NO_ADJUDICADA = "NO_ADJUDICADA"
    DECLINADA = "DECLINADA"

class FileStatus(str, Enum):
    PENDIENTE = "PENDIENTE"
    PROCESANDO = "PROCESANDO"
    PROCESADO = "PROCESADO"
    ERROR = "ERROR"
